version: 2
registries:
    maven:
        type: maven-repository
        url: https://maven.pkg.github.com/octocat
        username: dajay
        password: ${{secrets.MAVEN_TOKEN}}

updates:
    -   package-ecosystem: "maven" # See documentation for possible values
        directory: "/" # Location of package manifests
        target-branch: "main"
        schedule:
            interval: "daily"
        registries:
            - maven