swagger: "2.0"
info:
  title: Novaxium - Arbres organisationnels
  version: "1.0.0"
host: 127.0.0.1:8080
basePath: /api
schemes: [ http, https ]
consumes: [ application/json ]
produces: [ application/json ]

paths:
  /arbre-organisationnel:
    get:
      security:
        - bearerAuth: []
      operationId: lister
      summary: Liste des arbres organisationnels
      responses:
        "200":
          description: Succés
          schema:
            type: array
            items:
              $ref: '#/definitions/ArbreOrganisationnel'
        "400":
          description: Bad Request
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires

    post:
      security:
        - bearerAuth: []
      summary: Créer un nouvel arbre organisationnel
      operationId: creer
      parameters:
        - in: body
          name: arbre
          schema:
            $ref: '#/definitions/ArbreOrganisationnel'
      responses:
        "200":
          description: Succès
          schema:
            $ref: '#/definitions/ArbreOrganisationnel'
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "409":
          description: Un autre arbre organisationnel existe déjà avec le même code

    put:
      security:
        - bearerAuth: []
      operationId: modifier
      summary: Modifier un arbre organisationnel
      parameters:
        - in: body
          name: arbre
          schema:
            $ref: '#/definitions/ArbreOrganisationnel'
      responses:
        "200":
          description: Succès
          schema:
            $ref: '#/definitions/ArbreOrganisationnel'
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "404":
          description: L'arbre organisationnel n'existe pas
        "409":
          description: Un autre arbre organisationnel existe déjà avec le même code

  /arbre-organisationnel/{uuid}:
    get:
      security:
        - bearerAuth: []
      operationId: consulter
      parameters:
        - in: path
          type: string
          format: uuid
          description: Uuid de l'arbre organisationnel
          required: true
          name: uuid
      summary: Consulter l'arbre organisationnel
      responses:
        "200":
          description: Succès
          schema:
            $ref: '#/definitions/ArbreOrganisationnel'
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "404":
          description: L'arbre organisationnel n'existe pas

    delete:
      summary: Supprimer l'arbre organisationnel
      operationId: supprimer
      parameters:
        - in: path
          required: true
          type: string
          format: uuid
          name: uuid
          description: Uuid de l'arbre organisationnel
      responses:
        "200":
          description: Succès
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "404":
          description: L'arbre organisationnel n'existe pas

  /arbre-organisationnel/{uuid}/noeuds-organisationnels:
    get:
      security:
        - bearerAuth: []
      operationId: listerNoeudsOrganisationnels
      summary: Liste des noeuds de l'arbres organisationnel
      parameters:
        - in: path
          name: uuid
          format: uuid
          type: string
          required: true
          description: Uuid de l'arbre organisationnel
      responses:
        "200":
          description: Succés
          schema:
            type: array
            items:
              $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/commons.yaml#/definitions/NoeudOrganisationnel'
        "400":
          description: Bad Request
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "404":
          description: Arbre introuvable


definitions:
  ArbreOrganisationnel:
    type: object
    required:
    - code
    - libelle
    - dateDebut
    properties:
      uuid:
        type: string
        format: uuid
      code:
        type: string
      libelle:
        type: string
      dateDebut:
        type: string
        format: date
      dateFin:
        type: string
        format: date
      exhaustif:
        type: boolean
      affectationMultiple:
        type: boolean
      refAutorisation:
        type: boolean
