swagger: "2.0"
info:
  title: Novaxium - Arbre de Rôles
  version: "1.0.0"
host: 127.0.0.1:8080
basePath: /api
schemes: [ http, https ]
consumes: [ application/json ]
produces: [ application/json ]

paths:
  /arbre-roles:
    get:
      security:
        - bearerAuth: []
      operationId: lister
      summary: Liste des arbres de rôles
      parameters:
        - in: query
          name: type
          description: Filtre sur le type d'arbre de rôles
          type: string
          enum: [GROUPE, ETABLISSEMENT]
      responses:
        "200":
          description: Succés
          schema:
            title: ListerResponse
            type: array
            items:
              $ref: '#/definitions/ArbreRole'
        "400":
          description: Bad Request
        "401":
          description: Credentials invalides
        "404":
          description: Organisation ou utilisateur introuvable

    post:
      security:
        - bearerAuth: []
      summary: Créer un nouvel arbre de rôles
      operationId: creer
      parameters:
        - in: body
          name: arbre
          schema:
            $ref: '#/definitions/ArbreRole'
      responses:
        "200":
          description: Succès
          schema:
            $ref: '#/definitions/ArbreRole'
        "401":
          description: Credentials invalides

    put:
      security:
        - bearerAuth: []
      operationId: modifier
      summary: Caractéristiques de l'arbre de rôles
      parameters:
        - in: body
          name: arbre
          schema:
            $ref: '#/definitions/ArbreRole'
      responses:
        "200":
          description: Succès
          schema:
            $ref: '#/definitions/ArbreRole'
        "400":
          description: Bad request response
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires

  /arbre-roles/{uuid}:
    get:
      security:
        - bearerAuth: []
      operationId: consulter
      parameters:
        - in: path
          type: string
          format: uuid
          description: Uuid de l'arbre de rôle
          required: true
          name: uuid
      summary: Consulter l'arbre de rôles
      responses:
        "200":
          description: Succès
          schema:
            $ref: '#/definitions/ArbreRole'
        "404":
          description: L'arbre de rôle n'existe pas

    delete:
      security:
        - bearerAuth: []
      summary: Supprimer l'arbre de rôles
      operationId: supprimer
      parameters:
        - in: path
          required: true
          type: string
          format: uuid
          name: uuid
          description: Uuid de l'arbre de rôles
      responses:
        "200":
          description: Succès
        "400":
          description: Bad request response
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "404":
          description: L'arbre rôles n'existe pas

  /arbre-roles/{uuid}/roles:
    get:
      security:
        - bearerAuth: []
      operationId: listerRoles
      summary: Liste des rôles de l'arbre de rôles
      parameters:
        - in: path
          name: uuid
          format: uuid
          type: string
          required: true
          description: Uuid de l'arbre de rôles
      responses:
        "200":
          description: Succès
          schema:
            type: array
            items:
              $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/commons.yaml#/definitions/Role'
        "400":
          description: Bad request response
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "404":
          description: L'arbre rôles n'existe pas

definitions:
  ArbreRole:
    type: object
    required:
    - type
    - code
    - libelle
    - description
    properties:
      type:
        $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/enums.yaml#/definitions/TypeArbreRoleEnum'
      code:
        type: string
      uuid:
        type: string
        format: uuid
      libelle:
        type: string
      description:
        type: string
      actif:
        type: boolean
      arbreGroupeUuid:
        type: string
        format: uuid
      roleGroupeUuid:
        type: string
        format: uuid
