swagger: "2.0"
info:
  title: Novaxium - Commons
  version: "1.0.0"

# Hack pour la génération MAVEN
paths:
  /dummy:

definitions:

  Erreur:
    required:
      - code
    properties:
      champ:
        type: string
      code:
        $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/erreurs.yaml#/definitions/ErreurFonctionnelleEnum'

  Contexte:
    properties:
      token:
        type: string
      organisationCourante:
        type: string
      etablissementCourant:
        type: string
      organisations:
        type: array
        items:
          $ref: '#/definitions/Organisation'
      etablissements:
        type: array
        items:
          $ref: '#/definitions/Etablissement'
      fonctionnalites:
        type: array
        items:
          type: string

  Organisation:
    properties:
      uuid:
        type: string
        format: uuid
      nom:
        type: string
      code:
        type: string
      codePays:
        type: string
      nombreEtablissements:
        type: integer
      paysUuid:
        type: string
        format: uuid
      status:
        $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/enums.yaml#/definitions/StatusOrganisationEnum'
      type:
        $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/enums.yaml#/definitions/TypeOrganisationEnum'
      logo:
        type: string
        format: uuid
      adresse:
        $ref: '#/definitions/Adresse'

  Etablissement:
    properties:
      code:
        type: string
      nom:
        type: string

  Pays:
    properties:
      nom:
        type: string
      codeIso2:
        type: string
      codeIso3:
        type: string
      codeNumerique:
        type: integer

  Profil:
    type: object
    required:
    - code
    - libelle
    - description
    properties:
      uuid:
        type: string
        format: uuid
      code:
        type: string
      libelle:
        type: string
      description:
        type: string
      suppressionAutorisee:
        type: boolean
      type:
        $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/enums.yaml#/definitions/TypeFonctionnaliteEnum'

  Adresse:
    type: object
    required:
      - adresse
      - zip
      - ville
    properties:
      adresse:
        type: string
      complement:
        type: string
      zip:
        type: string
      ville:
        type: string

  NoeudOrganisationnel:
    type: object
    required:
    - libelle
    - description
    - arbreOrganisationnelUuid
    - children
    properties:
      uuid:
        type: string
        format: uuid
      libelle:
        type: string
      description:
        type: string
      parentUuid:
        type: string
        format: uuid
      children:
        type: array
        items:
          $ref: '#/definitions/NoeudOrganisationnel'
      etablissementUuid:
        type: string
        format: uuid
      arbreOrganisationnelUuid:
        type: string
        format: uuid
      typeUuid:
        type: string
        format: uuid
      supprimable:
        type: boolean

  Role:
    type: object
    required:
    - arbreRoleUuid
    - profilUuid
    - code
    - libelle
    - description
    properties:
      libelle:
        type: string
      code:
        type: string
      uuid:
        type: string
        format: uuid
      description:
        type: string
      profilUuid:
        type: string
        format: uuid
      administration:
        type: boolean
        default: false
      rolesAutorises:
        type: array
        items:
          $ref: '#/definitions/Role'
      parentUuid:
        type: string
        format: uuid
      arbreRoleUuid:
        type: string
        format: uuid

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

