swagger: "2.0"
info:
  title: LINKIAxium - Contexte
  version: "1.0.0"
host: 127.0.0.1:8080
basePath: /api
schemes: [ http, https ]
consumes: [ application/json ]
produces: [ application/json ]

paths:
  /contexte/changerOrganisation/{codeOrganisation}:
    get:
      operationId: changerOrganisation
      summary: Changer d'organisation
      parameters:
        - in: path
          name: codeOrganisation
          required: true
          schema:
            type: string

      responses:
        "200":
          description: Succés
          schema:
            $ref: '#/definitions/ChangerContexteResponse'
        "404":
          description: Organisation inconnue

  /contexte/changerEtablissement/{codeEtablissement}:
    get:
      operationId: changerEtablissement
      summary: Changer d'etablissement
      parameters:
        - in: path
          name: codeEtablissement
          required: true
          schema:
            type: string

      responses:
        "200":
          description: Succés
          schema:
            $ref: '#/definitions/ChangerContexteResponse'
        "404":
          description: Etablissement inconnu

definitions:
  ChangerContexteResponse:
    type: object
    properties:
      contexte:
        $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/commons.yaml#/definitions/Contexte'
