swagger: "2.0"
info:
  title: LINKIAxium - Enums communes au modele JPA
  version: "1.0.0"

# Les enums décrites dans ce fichier sont le mirroir de celles du modele jpa (LINKIA-entities / fr.redfroggy.LINKIAs5.model.**Enum)

# Hack pour la génération MAVEN
paths:
  /dummy:

definitions:
  # fr.redfroggy.LINKIAs5.model.core.enums.FonctionnaliteEnum
  FonctionnaliteEnum:
    type: string
    enum:
      - CRM_CONTACT_LISTE
      - CRM_PRESCRIPTEURS_LISTE
      - CRM_CAMPAGNES_LISTE
      - CRM_CONCURRENCE_LISTE
      - SEJOURS_EN_COURS_LISTE
      - SEJOURS_ABSENCES_LISTE
      - SEJOURS_CONTRATS_AVENANTS_LISTE
      - SEJOURS_EVENEMENTS_ELEMENTS_VARIABLES_LISTE
      - SEJOURS_DOSSIER_ADMINISTRATIF_LISTE
      - FACTURATION_PROCEDURE_LISTE
      - FACTURATION_SEJOUR_LISTE
      - FACTURATION_HORS_SEJOUR_LISTE
      - ENCAISDECAIS_REGL_MANUELS_LISTE
      - ENCAISDECAIS_PRELEV_VIREM_LISTE
      - ENCAISDECAIS_LIENS_TRESORIE_LISTE
      - ENCAISDECAIS_SOLDE_CLIENT_RELANCES_LISTE
      - AIDE_SOCIALE_ARGENT_POCHE_LISTE
      - AIDE_SOCIALE_DECLARATIF_DEPARTEMENTS_LISTE
      - AIDE_SOCIALE_NOTIFICATIONS_LISTE
      - AIDE_SOCIALE_RESSOURCES_CHARGES_LISTE
      - DEMARCHE_QUALITE_DEMARCHE_QUALITE_LISTE
      - DEMARCHE_QUALITE_ENQUETES_QUESTIONNAIRES_LISTE
      - DEMARCHE_QUALITE_EVALUATIONS_INTERNES_LISTE
      - DEMARCHE_QUALITE_EVALUATIONS_INTERNES_AJOUT
      - DEMARCHE_QUALITE_EVALUATIONS_INTERNES_DETAIL
      - DEMARCHE_QUALITE_EVALUATIONS_INTERNES_MODIF
      - DEMARCHE_QUALITE_EVENEMENTS_INDESIRABLES_LISTE
      - DEMARCHE_QUALITE_PLAN_AMELIORATION_CONTINUE_LISTE
      - PORTAIL_FAMILLE_JEUX_LISTE
      - PORTAIL_FAMILLE_MESSAGERIE_LISTE
      - PORTAIL_FAMILLE_PHOTOS_LISTE
      - PORTAIL_FAMILLE_PRESSE_LISTE
      - STRUCTURE_JURIDIQUE_LISTE
      - STRUCTURE_JURIDIQUE_AJOUT
      - STRUCTURE_JURIDIQUE_DETAIL
      - STRUCTURE_JURIDIQUE_MODIF
      - STRUCTURE_JURIDIQUE_IMPORT
      - WEBSERVICES_CATALOGUE_LISTE
      - WEBSERVICES_AUTORISATIONS_LISTE
      - WEBSERVICES_AUTORISATIONS_AJOUT
      - WEBSERVICES_AUTORISATIONS_DETAIL
      - WEBSERVICES_AUTORISATIONS_MODIF
      - ADMIN_MODULE_CRM
      - ADMIN_MODULE_SEJOURS
      - ADMIN_MODULE_FACTURATION
      - ADMIN_MODULE_ENCAISDECAIS
      - ADMIN_MODULE_AIDE_SOCIALE
      - REF_EVAL_MODELE_LISTE
      - REF_EVAL_MODELE_AJOUT
      - REF_EVAL_MODELE_MODIF
      - REF_EVAL_MODELE_IMPORT
      - FONCTION_GENERIQUE_LISTE
      - ADMIN_MODULE_PORTAIL_FAMILLE
      - ADMIN_MODULE_TRANSVERSAL
      - PROFILS_LISTE
      - PROFILS_AJOUT
      - PROFILS_DETAIL
      - PROFILS_MODIF
      - PROFILS_SUPPR
      - ARBRES_ROLES_LISTE
      - ARBRES_ROLES_AJOUT
      - ARBRES_ROLES_DETAIL
      - ARBRES_ROLES_MODIF
      - ROLES_LISTE
      - ROLES_AJOUT
      - ROLES_DETAIL
      - ROLES_MODIF
      - DROITS_PROFILS_LISTE
      - DROITS_PROFILS_AJOUTER_MODIFIER
      - ETABL_LISTE
      - ETABL_AJOUT
      - ETABL_DETAIL
      - ETABL_MODIF_CARACTERISTIQUES
      - ETABL_MODIF_ACTIVITES
      - ETABL_IMPORT
      - SIEGES_LISTE
      - SIEGES_AJOUT
      - SIEGES_DETAIL
      - SIEGES_MODIF_CARACTERISTIQUES
      - SIEGES_MODIF_ACTIVITES
      - MODELES_ORGA_LISTE
      - MODELES_ORGA_AJOUT
      - MODELES_ORGA_DETAIL
      - MODELES_ORGA_MODIF
      - NOEUDS_ORGA_LISTE
      - NOEUDS_ORGA_AJOUT
      - NOEUDS_ORGA_DETAIL
      - NOEUDS_ORGA_MODIF
      - NOEUDS_ORGA_SUPPR
      - AFFECT_ETAB_LISTE
      - AFFECT_ETAB_MODIF
      - UTILISATEURS_LISTE
      - UTILISATEURS_AJOUT
      - UTILISATEURS_DETAIL
      - UTILISATEURS_MODIF_CARACTERISTIQUES
      - UTILISATEURS_REINIT_PWD_QUEST
      - UTILISATEURS_GESTION_CLE_SECRETE_OTP
      - UTILISATEURS_AUTORISATION_LISTE
      - UTILISATEURS_AUTORISATION_DETAIL
      - UTILISATEURS_AUTORISATION_AJOUT
      - UTILISATEURS_VOIR_EN_COURS_CREATION
      - APP_EXTERNES_LISTE
      - APP_EXTERNES_AJOUT
      - APP_EXTERNES_DETAIL
      - APP_EXTERNES_MODIF_CARACTERISTIQUES
      - APP_EXTERNES_MODIF_FONCTIONNALITES
      - TRADUCTION_LISTE
      - TRADUCTION_MODIF
      - REFERENCES_LISTE
      - REFERENCES_AJOUT
      - REFERENCES_DETAIL
      - REFERENCES_MODIF
      - TRACABILITE_LISTE
      - GED_LISTE
      - ANNUAIRE_LISTE
      - ORGANISATIONS_LISTE
      - ORGANISATIONS_AJOUT
      - ORGANISATIONS_DETAIL
      - ORGANISATIONS_MODIF_CARACTERISTIQUES
      - ORGANISATIONS_AJOUT_ETABLISSEMENT
      - ORGANISATIONS_MODIF_ETABLISSEMENT
      - PACKAGES_MODULES_LISTE
      - PACKAGES_MODULES_AJOUT
      - PACKAGES_MODULES_MODIFIER
      - MODULES_LISTE
      - MODULES_AJOUT
      - MODULES_MODIF_CARACTERISTIQUES
      - MODULES_DEPLACER
      - ACTIVITES_AJOUT
      - ACTIVITES_DETAIL
      - ACTIVITES_MODIF_CARACTERISTIQUES
      - ACTIVITES_DEPLACER
      - PAYS_LISTE
      - PAYS_DETAIL
      - PAYS_MODIF_REFERENCES
      - DIAG_LISTE
      - DIAG_DETAIL
      - UTILISATIONS_LISTE
      - TFONC1
      - TFONC2

  # fr.redfroggy.LINKIAs5.model.core.enums.QuestionSecreteEnum
  QuestionSecreteEnum:
    type: string
    enum:
      - NOM_JF_MERE
      - RUE_ENFANT
      - PLAT_PREFERE
      - NOM_ANIMAL_COMPAGNIE
      - NOM_PROFESSEUR_FAVORI
      - VILLE_PREFEREE
      - LIVRE_PREFEREE
      - OEUVRE_ART_PREFEREE
      - SPORTIF_PREFEREE
      - AUTEUR_FAVORI

  # fr.redfroggy.LINKIAs5.model.core.enums.TypeArbreRoleEnum
  TypeArbreRoleEnum:
    type: string
    enum:
      - GROUPE
      - ETABLISSEMENT

  # fr.redfroggy.LINKIAs5.model.core.enums.TypeFonctionnaliteEnum
  TypeFonctionnaliteEnum:
    type: string
    enum:
      - UTILISATEUR
      - ADMIN_ORGANISATION
      - ADMIN_PLATEFORME
      - ADMIN_redfroggy
      - ADMIN_NX
