swagger: "2.0"
info:
  title: Novaxium - Noeuds organisationnels
  version: "1.0.0"
host: 127.0.0.1:8080
basePath: /api/admin
schemes: [ http, https ]
consumes: [ application/json ]
produces: [ application/json ]

paths:
  /noeud-organisationnel/lister/{arbreUuid}:
    get:
      security:
        - bearerAuth: []
      operationId: lister
      summary: Liste des noeuds de l'arbres organisationnel
      parameters:
        - in: path
          name: arbreUuid
          format: uuid
          type: string
          required: true
          description: Uuid de l'arbre organisationnel
      responses:
        "200":
          description: Succés
          schema:
            type: array
            items:
              $ref: '#/definitions/NoeudOrganisationnel'
        "400":
          description: Bad Request
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "404":
          description: Arbre introuvable

  /noeud-organisationnel/consulter/{uuid}:
    get:
      security:
        - bearerAuth: []
      operationId: consulter
      parameters:
        - in: path
          type: string
          format: uuid
          description: Uuid du noeud organisationnel
          required: true
          name: uuid
      summary: Consulter un noeud organisationnel
      responses:
        "200":
          description: Succès
          schema:
            $ref: '#/definitions/NoeudOrganisationnel'
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "404":
          description: Le noeud organisationnel n'existe pas


  /noeud-organisationnel/creer:
    put:
      security:
        - bearerAuth: []
      summary: Créer un nouveau noeud organisationnel
      operationId: creer
      parameters:
        - in: body
          name: noeud
          schema:
            $ref: '#/definitions/NoeudOrganisationnel'
      responses:
        "200":
          description: Succès
          schema:
            $ref: '#/definitions/NoeudOrganisationnel'
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires

  /noeud-organisationnel/modifier:
    post:
      security:
        - bearerAuth: []
      operationId: modifier
      summary: Modifier un noeud organisationnel
      parameters:
        - in: body
          name: noeud
          schema:
            $ref: '#/definitions/NoeudOrganisationnel'
      responses:
        "200":
          description: Succès
          schema:
            $ref: '#/definitions/NoeudOrganisationnel'
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "404":
          description: Le noeud organisationnel n'existe pas

  /noeud-organisationnel/supprimer/{uuid}:
    delete:
      summary: Supprimer l'arbre organisationnel
      operationId: supprimer
      parameters:
        - in: path
          required: true
          type: string
          format: uuid
          name: uuid
          description: Uuid de l'arbre organisationnel
      responses:
        "200":
          description: Succès
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "404":
          description: Le noeud n'existe pas

  /noeud-organisationnel/modifier-parents:
    post:
      security:
        - bearerAuth: []
      operationId: modifierParents
      summary: Sauvegarder la liste des noeuds d'un arbre organisationnel
      parameters:
        - in: body
          name: noeuds
          required: true
          schema:
            type: array
            items:
              $ref: '#/definitions/NoeudOrganisationnel'
          description: La liste des noeuds organisationnels à modifier
      responses:
        "200":
          description: succès
          schema:
            type: array
            items:
              $ref: '#/definitions/NoeudOrganisationnel'
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires

definitions:
  NoeudOrganisationnel:
    type: object
    required:
    - uuid
    - libelle
    - description
    - arbreOrganisationnelUuid
    - children
    properties:
      uuid:
        type: string
        format: uuid
      libelle:
        type: string
      description:
        type: string
      parentUuid:
        type: string
        format: uuid
      children:
        type: array
        items:
          $ref: '#/definitions/NoeudOrganisationnel'
      etablissementUuid:
        type: string
        format: uuid
      arbreOrganisationnelUuid:
        type: string
        format: uuid
      typeUuid:
        type: string
        format: uuid
      supprimable:
        type: boolean