swagger: "2.0"
info:
  title: Novaxium - Noeuds organisationnels
  version: "1.0.0"
host: 127.0.0.1:8080
basePath: /api
schemes: [ http, https ]
consumes: [ application/json ]
produces: [ application/json ]

paths:
  /noeud-organisationnel:
    post:
      security:
        - bearerAuth: []
      summary: Créer un nouveau noeud organisationnel
      operationId: creer
      parameters:
        - in: body
          name: noeud
          schema:
            $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/commons.yaml#/definitions/NoeudOrganisationnel'
      responses:
        "200":
          description: Succès
          schema:
            $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/commons.yaml#/definitions/NoeudOrganisationnel'
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires

    put:
      security:
        - bearerAuth: []
      operationId: modifier
      summary: Modifier un noeud organisationnel
      parameters:
        - in: body
          name: noeud
          schema:
            $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/commons.yaml#/definitions/NoeudOrganisationnel'
      responses:
        "200":
          description: Succès
          schema:
            $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/commons.yaml#/definitions/NoeudOrganisationnel'
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "404":
          description: Le noeud organisationnel n'existe pas

  /noeud-organisationnel/{uuid}:
    get:
      security:
        - bearerAuth: []
      operationId: consulter
      parameters:
        - in: path
          type: string
          format: uuid
          description: Uuid du noeud organisationnel
          required: true
          name: uuid
      summary: Consulter un noeud organisationnel
      responses:
        "200":
          description: Succès
          schema:
            $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/commons.yaml#/definitions/NoeudOrganisationnel'
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "404":
          description: Le noeud organisationnel n'existe pas

    delete:
      summary: Supprimer l'arbre organisationnel
      operationId: supprimer
      parameters:
        - in: path
          required: true
          type: string
          format: uuid
          name: uuid
          description: Uuid de l'arbre organisationnel
      responses:
        "200":
          description: Succès
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "404":
          description: Le noeud n'existe pas

  /noeud-organisationnel/modifier-parents:
    put:
      security:
        - bearerAuth: []
      operationId: modifierParents
      summary: Sauvegarder la liste des noeuds d'un arbre organisationnel
      parameters:
        - in: body
          name: noeuds
          required: true
          schema:
            type: array
            items:
              $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/commons.yaml#/definitions/NoeudOrganisationnel'
          description: La liste des noeuds organisationnels à modifier
      responses:
        "200":
          description: succès
          schema:
            type: array
            items:
              $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/commons.yaml#/definitions/NoeudOrganisationnel'
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires

