swagger: "2.0"
info:
  title: Novaxium - Organisations
  version: "1.0.0"
host: 127.0.0.1:8080
basePath: /api
schemes: [ http, https ]
consumes: [ application/json ]
produces: [ application/json ]

paths:
  /organisation:
    get:
      security:
        - bearerAuth: []
      operationId: lister
      summary: Liste des organisations

      responses:
        "200":
          description: Succés
          schema:
            type: array
            items:
              $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/commons.yaml#/definitions/Organisation'

        "401":
          description: Credentials invalides
        "404":
          description: Organisation ou utilisateur introuvable

    post:
      security:
        - bearerAuth: []
      operationId: creer
      summary: Création d'une organisation
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/commons.yaml#/definitions/Organisation'
      responses:
        "200":
          description: Succés
          schema:
            $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/commons.yaml#/definitions/Organisation'
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "404":
          description: Aucune organisation pour le code

    put:
      security:
        - bearerAuth: []
      operationId: modifier
      summary: Modification d'une organisation
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/commons.yaml#/definitions/Organisation'
      responses:
        "200":
          description: Succés
          schema:
            $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/commons.yaml#/definitions/Organisation'
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "404":
          description: Aucune organisation pour le code

  /organisation/{uuid}:
    get:
      security:
        - bearerAuth: []
      operationId: consulter
      summary: Consulter une organisation

      parameters:
        - in: path
          name: uuid
          required: true
          schema:
          type: string
          format: uuid
      responses:
        "200":
          description: Succés
          schema:
            $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/commons.yaml#/definitions/Organisation'
    delete:
      security:
        - bearerAuth: []
      operationId: supprimer
      summary: Supprimer une organisation
      parameters:
        - in: path
          name: uuid
          required: true
          type: string
          format: uuid

      responses:
        "200":
          description: Succés
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "404":
          description: Aucune organisation pour l'uuid