swagger: "2.0"
info:
  title: Novaxium - Profil
  version: "1.0.0"
host: 127.0.0.1:8080
basePath: /api
schemes: [ http, https ]
consumes: [ application/json ]
produces: [ application/json ]

paths:
  /profil/liste:
    get:
      security:
        - bearerAuth: []
      operationId: lister
      summary: Liste des profils

      responses:
        "200":
          description: Succés
          schema:
            type: array
            items:
              $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/commons.yaml#/definitions/Profil'
        "400":
          description: Credentials invalides
        "404":
          description: Organisation ou utilisateur introuvable

  /profil/consulter/{uuid}:
    get:
      security:
        - bearerAuth: []
      operationId: consulter
      summary: Consulter un profil
      parameters:
        - in: path
          name: uuid
          format: uuid
          type: string
          required: true

      responses:
        "200":
          description: Succés
          schema:
            $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/commons.yaml#/definitions/Profil'
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "404":
          description: Aucun profil pour le code

  /profil/creer:
    put:
      security:
        - bearerAuth: []
      operationId: creer
      summary: Création d'un profil
      parameters:
        - in: body
          name: profil
          required: true
          schema:
            $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/commons.yaml#/definitions/Profil'
      responses:
        "200":
          description: Succés
          schema:
            $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/commons.yaml#/definitions/Profil'
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "409":
          description: Un profil existe déjà avec le même code

  /profil/modifier:
    post:
      security:
        - bearerAuth: []
      operationId: modifier
      summary: Modifier un profil
      parameters:
        - in: body
          name: profil
          required: true
          schema:
            $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/commons.yaml#/definitions/Profil'
      responses:
        "200":
          description: Succés
          schema:
            $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/commons.yaml#/definitions/Profil'
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "404":
          description: Aucun profil pour le code
        "409":
          description: Un profil existe déjà avec le même code

  /profil/supprimer/{uuid}:
    delete:
      security:
        - bearerAuth: []
      operationId: supprimer
      summary: Supprimer un profil sans rôles
      parameters:
        - in: path
          name: uuid
          required: true
          type: string
          format: uuid

      responses:
        "200":
          description: Succés
        "400":
          description: Un ou plusieurs rôles utilisent ce profil
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "404":
          description: Aucun profil pour le code
