swagger: "2.0"
info:
  title: Novaxium - Rôles
  version: "1.0.0"
host: 127.0.0.1:8080
basePath: /api
schemes: [ http, https ]
consumes: [ application/json ]
produces: [ application/json ]

paths:
  /role:
    post:
      security:
        - bearerAuth: []
      operationId: creer
      summary: Creer un role
      parameters:
        - in: body
          name: role
          schema:
            $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/commons.yaml#/definitions/Role'
          description: Le rôle à créer.
      responses:
        "200":
          description: succès
          schema:
            $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/commons.yaml#/definitions/Role'
        "400":
          description: Ce role n'est pas modifiable
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "409":
          description: Un role existe déjà avec le même code

    put:
      security:
        - bearerAuth: []
      operationId: modifier
      summary: Modifier un rôle
      parameters:
        - in: body
          name: role
          schema:
            $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/commons.yaml#/definitions/Role'
          description: le rôle à modifier
      responses:
        "200":
          description: Succès
          schema:
            $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/commons.yaml#/definitions/Role'
        "400":
          description: Ce rôle n'est pas modifiable
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "404":
          description: Aucun rôle pour le code

  /role/{uuid}:
    get:
      security:
        - bearerAuth: []
      operationId: consulter
      parameters:
        - in: path
          name: uuid
          format: uuid
          type: string
          required: true
          description: Uuid du rôle
      responses:
        "200":
          description: Succès
          schema:
            $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/commons.yaml#/definitions/Role'
        "400":
          description: Bad request response
        "401":
          description: Credentials invalides
        "404":
          description: Le rôle n'existe pas

    delete:
      security:
        - bearerAuth: []
      summary: Supprimer un rôle
      operationId: supprimer
      parameters:
        - in: path
          name: uuid
          format: uuid
          type: string
          required: true
          description: Uuid du rôle
      responses:
        "200":
          description: Succès
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "404":
          description: Le rôle n'existe pas

  /role/modifier-parents:
    put:
      security:
        - bearerAuth: []
      operationId: modifierParents
      summary: Sauvegarder la liste des rôle d'un arbre
      parameters:
        - in: body
          name: roles
          required: true
          schema:
            type: array
            items:
              $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/commons.yaml#/definitions/Role'
          description: La liste des rôles à modifier
      responses:
        "200":
          description: succès
          schema:
            type: array
            items:
              $ref: 'https://raw.githubusercontent.com/dajay/swagger-doc/master/commons.yaml#/definitions/Role'
        "400":
          description: La liste n'est pas modifiable
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "404":
          description: La liste n'existe pas
