swagger: "2.0"
info:
  title: LINKIAxium - Rôles
  version: "1.0.0"
host: 127.0.0.1:8080
basePath: /api/admin
schemes: [ http, https ]
consumes: [ application/json ]
produces: [ application/json ]

paths:
  /role/lister/{arbreUuid}:
    get:
      security:
        - bearerAuth: []
      operationId: lister
      summary: Liste des rôles de l'arbre de rôles
      parameters:
        - in: path
          name: arbreUuid
          format: uuid
          type: string
          required: true
          description: Uuid de l'arbre de rôles
      responses:
        "200":
          description: Succès
          schema:
            type: array
            items:
              $ref: '#/definitions/Role'
        "400":
          description: Bad request response
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "404":
          description: L'arbre rôles n'existe pas

  /role/consulter/{uuid}:
    get:
      security:
        - bearerAuth: []
      operationId: consulter
      parameters:
        - in: path
          name: uuid
          format: uuid
          type: string
          required: true
          description: Uuid du rôle
      responses:
        "200":
          description: Succès
          schema:
            $ref: '#/definitions/Role'
        "400":
          description: Bad request response
        "401":
          description: Credentials invalides
        "404":
          description: Le rôle n'existe pas

  /role/creer:
    put:
      security:
        - bearerAuth: []
      operationId: creer
      summary: Creer un role
      parameters:
        - in: body
          name: role
          schema:
            $ref: '#/definitions/Role'
          description: Le rôle à créer.
      responses:
        "200":
          description: succès
          schema:
            $ref: '#/definitions/Role'
        "400":
          description: Ce role n'est pas modifiable
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "409":
          description: Un role existe déjà avec le même code

  /role/modifier:
    post:
      security:
        - bearerAuth: []
      operationId: modifier
      summary: Modifier un rôle
      parameters:
        - in: body
          name: role
          schema:
            $ref: '#/definitions/Role'
          description: le rôle à modifier
      responses:
        "200":
          description: Succès
          schema:
            $ref: '#/definitions/Role'
        "400":
          description: Ce rôle n'est pas modifiable
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "404":
          description: Aucun rôle pour le code

  /role/supprimer/{uuid}:
    delete:
      summary: Supprimer un rôle
      operationId: supprimer
      parameters:
        - in: path
          name: uuid
          format: uuid
          type: string
          required: true
          description: Uuid du rôle
      responses:
        "200":
          description: Succès
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "404":
          description: Le rôle n'existe pas

  /role/modifier-parents:
    post:
      security:
        - bearerAuth: []
      operationId: modifierParents
      summary: Sauvegarder la liste des rôle d'un arbre
      parameters:
        - in: body
          name: body
          required: true
          schema:
            title: ModifierParentsRequest
            type: object
            required:
              - uuidArbreSelectionne
              - roles
            properties:
              uuidArbreSelectionne:
                type: string
                format: uuid
              roles:
                type: array
                items:
                  $ref: '#/definitions/Role'
          description: La liste des rôles à modifier
      responses:
        "200":
          description: succès
          schema:
            type: array
            items:
              $ref: '#/definitions/Role'
        "400":
          description: La liste n'est pas modifiable
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "404":
          description: La liste n'existe pas

definitions:
  Role:
    type: object
    required:
    - arbreRoleUuid
    - profilUuid
    - uuid
    - code
    - libelle
    - description
    properties:
      libelle:
        type: string
      code:
        type: string
      uuid:
        type: string
        format: uuid
      description:
        type: string
      profilUuid:
        type: string
        format: uuid
      administration:
        type: boolean
        default: false
      rolesAutorises:
        type: array
        items:
          $ref: '#/definitions/Role'
      parentUuid:
        type: string
        format: uuid
      arbreRoleUuid:
        type: string
        format: uuid
