swagger: "2.0"
info:
  title: Novaxium - Tokens de WebServices
  version: "1.0.0"
host: 127.0.0.1:8080
basePath: /api
schemes: [ http, https ]
consumes: [ application/json ]
produces: [ application/json ]

paths:
  /web-service-token/lister:
    get:
      security:
        - bearerAuth: []
      summary: Lister les tokens de WebServices
      operationId: lister
      responses:
        "200":
          description: Succès
          schema:
            type: array
            items:
              $ref: '#/definitions/WebServiceToken'
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires

  /web-service-token/consulter/{uuid}:
    get:
      security:
        - bearerAuth: []
      summary: Consulter les détails d'un token de WebService
      operationId: consulter
      parameters:
        - in: path
          name: uuid
          type: string
          format: uuid
          required: true
          description: UUID du token
      responses:
        "200":
          description: Succès
          schema:
            $ref: '#/definitions/WebServiceToken'
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "404":
          description: Token introuvable

  /web-service-token/creer:
    put:
      security:
        - bearerAuth: []
      operationId: creer
      summary: Creer un token de webservice
      parameters:
        - in: body
          name: token
          schema:
            $ref: '#/definitions/WebServiceToken'
          description: Le token à créer.
      responses:
        "200":
          description: succès
          schema:
            $ref: '#/definitions/WebServiceToken'
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "409":
          description: Un token existe déjà avec le même code

  /web-service-token/modifier:
    post:
      security:
        - bearerAuth: []
      operationId: modifier
      summary: Modifier un token
      parameters:
        - in: body
          name: token
          schema:
            $ref: '#/definitions/WebServiceToken'
          description: le token à modifier
      responses:
        "200":
          description: Succès
          schema:
            $ref: '#/definitions/WebServiceToken'
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "404":
          description: Token introuvable
        "409":
          description: Un token existe déjà avec le même code

  /web-service-token/supprimer/{uuid}:
    delete:
      security:
        - bearerAuth: []
      summary: Supprimer un token
      operationId: supprimer
      parameters:
        - in: path
          name: uuid
          format: uuid
          type: string
          required: true
          description: Uuid du token
      responses:
        "200":
          description: Succès
        "401":
          description: Credentials invalides
        "403":
          description: Vous ne disposez pas des droits nécessaires
        "404":
          description: Le rôle n'existe pas

definitions:
  WebServiceToken:
    type:
    required:
      - uuid
    properties:
      uuid:
        type: string
        format: uuid
      code:
        type: string
      libelle:
        type: string
      dateDebutActif:
        type: string
        format: date
      dateFinActif:
        type: string
        format: date
      actif:
        type: boolean
      hasPerimetreAppExterne:
        type: boolean
